Class variables moved to constructor to make them instance variables.
guorbit/utilities pull request #52
Opened 2023-07-31 13:34 UTC by 2684413S

The class variables were moved to the constructor so they become instance variables. The class variable 'preprocessing_seed = None' was removed because it already exists in the constructor as 'preprocessing_seed: Optional [int] = None' and been initialised.

2023-07-31 13:36 UTC, 2684413S commented on utilities/segmentation_utils/flowreader.py
> +        preprocessing_queue_image = None,
the variables that were added

2023-08-01 07:12 UTC, Sajtospoga01 requested changes

2023-08-01 07:12 UTC, Sajtospoga01 commented on utilities/segmentation_utils/flowreader.py
> +        preprocessing_queue_image = None,
You also need to provide the variable for the mask preprocessing queue

2023-08-01 07:12 UTC, Sajtospoga01 commented on utilities/segmentation_utils/flowreader.py
> +        self.shuffle_counter = shuffle_counter
Looks good 👌👌👌

2023-08-01 07:12 UTC, Sajtospoga01 commented on utilities/segmentation_utils/flowreader.py
> +        self.shuffle_counter = shuffle_counter
Also as a last comment if the tests have passed this way, we need to invest time into adding more tests and improve our existing ones

2023-08-01 09:49 UTC, 2684413S reviewed
the mask preprocessing queue variable has been added below the image preprocessing queue variable

2023-08-01 09:53 UTC, Sajtospoga01 approved these changes

2023-08-01 09:53 UTC, merged